Add animationImages support when using SDAnimatedImageView
SDWebImage/SDWebImage pull request #3113
Opened 2020-10-27 18:18 UTC by MoZhouqi

### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: ...

### Pull Request Description
Add `animationImages` support when using `SDAnimatedImageView`.
...

2020-10-28 02:10 UTC, kinarobin commented on SDWebImage/Core/SDAnimatedImageView.m
> +- (void)setAnimationImages:(NSArray<UIImage *> *)animationImages
Maybe this method should apply to `#if SD_UIKIT`.

2020-10-28 02:10 UTC, kinarobin commented on SDWebImage/Core/SDAnimatedImageView.m
>  }
Same! `self.animationImages` Just in UIKit, you should think about AppKit.

2020-10-28 05:47 UTC, MoZhouqi commented
@kinarobin Thanks for your suggestion, I have updated the code.

2020-10-28 11:49 UTC, kinarobin approved these changes

2020-10-29 03:27 UTC, dreampiggy commented
I wonder, what cause this issues ?
We override the super startAnimating: and setImage:, and setAnimations also use the super implementation.

If you use `UIImageView.aniamtionImages`, it shoud work as normal, because it's super's implementation

2020-10-29 05:42 UTC, MoZhouqi commented
> I wonder, what cause this issue ?
> 
> We override the super startAnimating: and setImage:, and setAnimations also use the super implementation.
> 
> If you use `UIImageView.aniamtionImages`, it shoud work as normal, because it's super's implementation

For example:
```objc
SDAnimatedImageView *imageView = [SDAnimatedImageView alloc] initWithFrame:frame];
imageView.animationImages = animationImages;
[imageView startAnimating];
imageView.hidden = NO;
```
There are two issues with the above code:
1. Although the default value of `autoPlayAnimatedImage` is `YES`, the animation is not playing automatically after setting a non-nil value on the `animationImages` property.
2. When `setHidden:` method is called,  `checkPlay` method will be invoked and then the animation will be stopped.

2020-10-29 06:49 UTC, dreampiggy commented
> > I wonder, what cause this issue ?
> > We override the super startAnimating: and setImage:, and setAnimations also use the super implementation.
> > If you use `UIImageView.aniamtionImages`, it shoud work as normal, because it's super's implementation
> 
> For example:
> 
> ```objc
> SDAnimatedImageView *imageView = [SDAnimatedImageView alloc] initWithFrame:frame];
> imageView.animationImages = animationImages;
> [imageView startAnimating];
> imageView.hidden = NO;
> ```
> 
> There are two issues with the above code:
> 
> 1. Although the default value of `autoPlayAnimatedImage` is `YES`, the animation is not playing automatically after setting a non-nil value on the `animationImages` property.
> 2. When `setHidden:` method is called,  `checkPlay` method will be invoked and then the animation will be stopped.

I see... This can be updated into the Unit Test (SDWebImage Tetsts), so that can ensure this will not be broken in later version.

2020-10-29 15:58 UTC, MoZhouqi commented
> > > I wonder, what cause this issue ?
> > > We override the super startAnimating: and setImage:, and setAnimations also use the super implementation.
> > > If you use `UIImageView.aniamtionImages`, it shoud work as normal, because it's super's implementation
> > 
> > 
> > For example:
> > ```objc
> > SDAnimatedImageView *imageView = [SDAnimatedImageView alloc] initWithFrame:frame];
> > imageView.animationImages = animationImages;
> > [imageView startAnimating];
> > imageView.hidden = NO;
> > ```
> > 
> > 
> > There are two issues with the above code:
> > 
> > 1. Although the default value of `autoPlayAnimatedImage` is `YES`, the animation is not playing automatically after setting a non-nil value on the `animationImages` property.
> > 2. When `setHidden:` method is called,  `checkPlay` method will be invoked and then the animation will be stopped.
> 
> I see... This can be updated into the Unit Test (SDWebImage Tetsts), so that can ensure this will not be broken in later version.

I've added the test cases for `animationImages`.

2020-10-30 02:50 UTC, dreampiggy approved these changes

2020-10-30 03:03 UTC, dreampiggy requested changes
I have another way to solve this problem, by leaving all the control to UIKit, we don't touch.

Remove all the changes to `SDAnimatedImageView`, only modify this method:

```objective-c
/// Check if it should be played
- (void)checkPlay
{
    // Only handle for SDAnimatedImage, leave UIAnimatedImage or animatedImages for super implementation control
    if (self.player && self.autoPlayAnimatedImage) {
        [self updateShouldAnimate];
        if (self.shouldAnimate) {
            [self startAnimating];
        } else {
            [self stopAnimating];
        }
    }
}
```

I have tested this also match your behavior, but it's more suitable and maintainable. I think, **SDAnimatedImageView should be a drop-in replacement for UIImageView**. So if super class implementation do something, we should call their instead and only handle the case we added (That `SDAnimatedImagePlayer` or `SDAnimatedImage`), not assume current iOS's behavior.

See:

![image](https://user-images.githubusercontent.com/6919743/97655327-c8727a80-1a9f-11eb-8e4d-ec14e2d919b3.png)

2020-10-30 07:46 UTC, MoZhouqi commented
> I have another way to solve this problem, by leaving all the control to UIKit, we don't touch.
> 
> Remove all the changes to `SDAnimatedImageView`, only modify this method:
> 
> ```objc
> /// Check if it should be played
> - (void)checkPlay
> {
>     // Only handle for SDAnimatedImage, leave UIAnimatedImage or animatedImages for super implementation control
>     if (self.player && self.autoPlayAnimatedImage) {
>         [self updateShouldAnimate];
>         if (self.shouldAnimate) {
>             [self startAnimating];
>         } else {
>             [self stopAnimating];
>         }
>     }
> }
> ```
> 
> I have tested this also match your behavior, but it's more suitable and maintainable. I think, **SDAnimatedImageView should be a drop-in replacement for UIImageView**. So if super class implementation do something, we should call their instead and only handle the case we added (That `SDAnimatedImagePlayer` or `SDAnimatedImage`), not assume current iOS's behavior.
> 
> For this issue, I think this `autoPlayAnimatedImage` should only effect `SDAnimatedImage`, we can update the code comment in header files about this.
> 
> See:
> 
> ![image](https://user-images.githubusercontent.com/6919743/97655327-c8727a80-1a9f-11eb-8e4d-ec14e2d919b3.png)

Yes I see, it is better, I have updated the code, the test cases and the code comment in header files.

2020-10-30 07:47 UTC, MoZhouqi commented
@dreampiggy Yes I see, it is better, I have updated the code, the test cases and the code comment in header files.

2020-10-30 07:49 UTC, dreampiggy approved these changes
Now it's better :)

2020-10-30 07:58 UTC, MoZhouqi commented
> Now it's better :)

🍻 Yes, the previous treatment is not perfect, I should also deal with other properties properly, such as `currentFrame`.

2020-11-03 02:26 UTC, merged