Add linker settings to prevent warning: `linking against a dylib which is not safe for use in application extensions`
SDWebImage/SDWebImage pull request #3545
Opened 2023-05-30 22:17 UTC by Iron-Ham

### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ] I have added the required tests to prove the fix/feature I am adding
* [ ] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [ ] I have run the lint and it passes (`pod lib lint`)

### Pull Request Description

When linking against `SDWebImage` as a Swift package, there are instances that can cause the following warning: `linking against a dylib which is not safe for use in application extensions`. 

Since this package doesn't actually use disallowed APIs, this PR:
* Forcefully tells the linker that it's okay.
* Sets the local build for `SDWebImage` to fail if we include a disallowed API.

2023-05-31 09:24 UTC, dreampiggy commented
unsafeFlags will break sub-dependnecy. Because this is hacky checked by Xcode's intergration with SPM. You should not use that for SDWebImage...

See:https://stackoverflow.com/questions/63064164/swift-package-dependency-with-unsafe-build-flags-target-integrity-error

2023-05-31 09:25 UTC, dreampiggy requested changes
Need another way for SPM to add this, not using unsafeFlags

2023-05-31 10:16 UTC, Iron-Ham commented
At present, there is no other way to add this to a Swift package other than unsafe flags.

2023-05-31 12:40 UTC, closed without merging

2023-05-31 12:56 UTC, dreampiggy commented
@Iron-Ham  A quick question:

Why your SPM use dynamic lib of SDWebImage ? I asume SPM always use static library of Swift target, isn't it ?

2023-06-01 04:05 UTC, dreampiggy commented
App -> Dynamic Target -> Third Party Libs like SDWebImage

This will cause the dependent SDWebImage finally become `Dynamic` in the main App ? SDWebImage itself will be bundled into a dynamic lib and linked into main App.

Sounds reasonable.


---

However, this annoying warning seems no good way to workaround. Can the `App` level or `Dynamic Target` level provide the linker flags which effect this ?